### ISSUE TITLE
Overlapping column content when use rowComponent

### ISSUE THREAD

**Issue by msantanais** [agranara/agnijs#3]
**Without rowComponent**
![image](https://user-images.githubusercontent.com/50163310/77386961-b4a2bf80-6dbe-11ea-8473-78ef28e46a42.png)
![1 edited](https://user-images.githubusercontent.com/50163310/77390011-457d9900-6dc7-11ea-9307-602dfda9f65c.jpg)

**Using rowComponent**
![image](https://user-images.githubusercontent.com/50163310/77386896-8cb35c00-6dbe-11ea-800a-9327358c6963.png)
![2 edited](https://user-images.githubusercontent.com/50163310/77390061-61813a80-6dc7-11ea-88c5-5428e44e5dab.jpg)

**Comment by agranara** [comment]
@Santana131001 can I see `columns` configuration when you use it?

**Comment by msantanais** [comment]
this one
![image](https://user-images.githubusercontent.com/50163310/77387560-5545af00-6dc0-11ea-90a4-527a35b86202.png)
![image](https://user-images.githubusercontent.com/50163310/77387742-ce450680-6dc0-11ea-85f9-40369bc6ae33.png)
or
![image](https://user-images.githubusercontent.com/50163310/77387629-83c38a00-6dc0-11ea-85fe-89b0153c7d5a.png)
this one ?

**Comment by agranara** [comment]
@Santana131001 yeah. So, internally, `DataGrid` compute "auto" width by using sample that defined by `sampleStart` and `sampleEnd` attribute, or explicitly set `width` inside `columns` attribute

![Solution](https://user-images.githubusercontent.com/41906688/77388378-80c99900-6dc2-11ea-9442-bde8d9b62171.png)

Can you set that and confirm again after trying it?

**Comment by msantanais** [comment]
![3 edited](https://user-images.githubusercontent.com/50163310/77390174-bd4bc380-6dc7-11ea-9bcb-468f46a35012.jpg)
